baseURL = "https://chaos502.github.io/"
languageCode = "zh-cn"
title = "My Blog"
theme = "PaperMod"

[params]
  author = "chaos502"
  showToc: true # 显示目录
  TocOpen: true # 自动展开目录
  autonumbering: true # 目录自动编号
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons: true
  defaultTheme = "auto"
  comments = true
  DateFormat = "YYYY-MM-DD"  # 日期格式化
  ShowFullTextinRSS = true   # RSS 输出全文
  description = "你的网站描述"
  keywords: [Blog, Portfolio, PaperMod]

[params.social]
  twitter = "yourTwitterHandle"
  github = "yourGithubUsername"
  linkedin = "yourLinkedinProfile"
  
[params.opengraph]
  image = "path/to/og-image.jpg"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.giscus]
  repo = "chaos502/chaos502blog"
  repoId = "R_kgDOOsH1cQ"
  category = "General"
  categoryId = "DIC_kwDOOsH1cc4CqTS4"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "top"
  lightTheme = "light"
  darkTheme = "dark"
  lang = "zh-CN"
  discussionTitle = ""
  discussionSubtitle = ""