baseURL = "https://CosmicHourglass.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"

[params]
  author = "CosmicHourglass"
  ShowReadingTime = true
  ShowPostNavLinks = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]
