baseURL = "https://chaos502.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"

[params]
  author = "chaos502"
  ShowReadingTime = true
  ShowPostNavLinks = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.giscus]
  repo = "chaos502/chaos502blog"
  repoId = "R_kgDOOsH1cQ"
  category = "General"
  categoryId = "DIC_kwDOOsH1cc4CqTS4"
  mapping: "pathname"
  strict: "0"
  reactionsEnabled: "1"
  emitMetadata: "0"
  inputPosition: "top"
  lightTheme: "light"
  darkTheme: "dark"
  lang: "zh-CN"
  discussionTitle: "" # 按需填写，评论框上方的标题
  discussionSubtitle: "" # 按需填写，评论框上方的副标题