baseURL = "https://chaos502.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "PaperMod"

[params]
  author = "chaos502"
  ShowReadingTime = true
  ShowPostNavLinks = true
  defaultTheme = "auto"
  comments = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.giscus]
  repo = "chaos502/chaos502blog"
  repoId = "R_kgDOOsH1cQ"
  category = "General"
  categoryId = "DIC_kwDOOsH1cc4CqTS4"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "top"
  lightTheme = "light"
  darkTheme = "dark"
  lang = "zh-CN"
  discussionTitle = ""
  discussionSubtitle = ""