name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # 监听 main 分支的推送事件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build Web
        run: hugo -D

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
          publish_branch: main
          EXTERNAL_REPOSITORY: CosmicHourglass/CosmicHourglass.github.io
          commit_message: auto deploy
